title: Sample DLS Website
remote_theme: WesPeacock/dls-theme
color_scheme: rc
github_repo_url: "https://github.com/WesPeacock/SampleWebsite/"

# license information for workshop content
license_name: "Creative Commons Attribution 4.0 International License"
license_url: "http://creativecommons.org/licenses/by/4.0/"
license_image_url: "https://i.creativecommons.org/l/by/4.0/88x31.png"

# required for building jekyll site locally
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
